### ISSUE TITLE
Return RFC7807 type errors

### ISSUE THREAD

**Issue by sagikazarmark** [openmeterio/openmeter#107]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Currently we return a custom error format to clients. While that's not necessarily a problem, some standardisation would be nice.

### Proposed Solution

Return errors formatted according to [RFC7807](https://datatracker.ietf.org/doc/html/rfc7807).

A library I've used in the past: https://github.com/moogar0880/problems

### Alternatives Considered

Given the size of the library, we could just implement our own problem types.

**Comment by sagikazarmark** [comment]
@tothandras is this done?

**Comment by tothandras** [comment]
@sagikazarmark let me know if you find this acceptable:
- https://github.com/openmeterio/openmeter/blob/next/api/openapi.yaml#L173
- https://github.com/openmeterio/openmeter/blob/next/pkg/models/problem.go

**Comment by sagikazarmark** [comment]
lgtm
