### ISSUE TITLE
Plug-n-play deploy a kubernetes pod usage metering

### ISSUE THREAD

**Issue by yairyairyair** [openmeterio/openmeter#119]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

I have a cluster and i want to know how much resources a namespace uses via metering the pods in it

### Proposed Solution

There is a demo already for it in examples but it is not prod ready, it is a common use-case that can be useful for many users of openmeter

**Comment by tothandras** [comment]
Hi @yairyairyair, we've just shipped this feature: https://openmeter.io/docs/ingestion/kubernetes
