### ISSUE TITLE
Create new subjects endpoint

### ISSUE THREAD

**Issue by sagikazarmark** [openmeterio/openmeter#214]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

The UI needs to figure out subjects from the returned data

### Proposed Solution

Create a new /subjects endpoint for a meter that returns all available subjects.

**Comment by tothandras** [comment]
#224
