### ISSUE TITLE
Python client

### ISSUE THREAD

**Issue by pbarker** [openmeterio/openmeter#266]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

A lot of AI code is written in Python, a nice client would be ideal!

### Proposed Solution

Likely generate it off the openapi spec

### Alternatives Considered

Might be nice to directly work it into something like FastAPI

**Comment by yujonglee** [comment]
+1

**Comment by tothandras** [comment]
I've just opened a PR for an initial version of the Python SDK. I'm looking forward to your feedback! Thank you! 🙂

**Comment by hekike** [comment]
@yujonglee @pbarker, what do you think? https://github.com/openmeterio/openmeter/pull/281

**Comment by pbarker** [comment]
lgtm thanks!

**Comment by yujonglee** [comment]
@hekike  Thanks for the quick PR. LGTM!
