### ISSUE TITLE
Add tracing support to Benthos collector

### ISSUE THREAD

**Issue by sagikazarmark** [openmeterio/openmeter#897]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.

### Problem Description

Cannot trace outgoing queries to OpenMeter.

### Proposed Solution

Implement OTEL tracing support for the `openmeter` output.

**Comment by chrisgacsal** [comment]
Done
