### ISSUE TITLE
CORS error on web client

### ISSUE THREAD

**Issue by dhrn** [openmeterio/openmeter#940]
### Preflight Checklist

- [ ] I have searched the [issue tracker](https://www.github.com/openmeterio/openmeter/issues) for an issue that matches the one I want to file, without success.
- [ ] I am not looking for support or already pursued the available [support channels](https://github.com/openmeterio/openmeter/issues/new/choose) without success.

### OpenMeter Version

1.0.0-beta.29

### Expected Behavior

I have simple next js with web integration in place. Im getting cors error for each query ?

![image](https://github.com/openmeterio/openmeter/assets/14145706/88bd478a-e0ed-4b9e-81af-06748038861f)

### Actual Behavior

Should be able hit server without cors error.

### Steps To Reproduce

Deploy simple next js app with integration as suggested here 

https://openmeter.io/blog/launchweek-1-day-4-consumer-portal#heading-how-can-openmeter-help

**Comment by sagikazarmark** [comment]
Thank you for reporting @dhrn !

We will investigate and get back to you. It's likely a web server misconfiguration.

**Comment by tothandras** [comment]
A fix has been rolled out; thanks for reporting, @dhrn!
